language: node_js

jobs:
  include:
# need to troubleshoot failure of test/fixtures/promise.js under node.js 13.
#    - node_js: 'node'
    - node_js: '12'
    - node_js: '10'
      env: TEST_ARGS='--no-check-coverage'

script: npm test -- $TEST_ARGS
